### ISSUE TITLE
迁移机器的时候，遇到下边问题

### ISSUE THREAD

**Issue by chanyying** [twang2218/gitlab-ce-zh#11]
`
Error executing action `run` on resource 'execute[/opt/gitlab/embedded/service/gitlab-shell/bin/gitlab-keys check-permissions]'
`
启动脚本：

` 

docker run -d \
    --hostname gitlab.shuidihuzhu.com \
    -p 80:80 \
    -p 443:443 \
    -p 7000:22\
    --name $1 \
    --restart unless-stopped \
    -v gitlab-config:/etc/gitlab \
    -v gitlab-logs:/var/log/gitlab \
    -v gitlab-data:/var/opt/gitlab \
    --network gitlab-net \
    chanyying/shuidi-gitlab:v1

`
用这个脚本重新构建的没事，但是我需要把旧机器的数据volumes拷贝到新的机器的/var/lib/docker/volumes下边。结果就出现了上述错误了。

请问有解决办法吗？

**Comment by twang2218** [comment]
跨服务器迁移应该使用 Gitlab 内置的备份恢复的机制，请参考官方文档：https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/raketasks/backup_restore.md

**Comment by chanyying** [comment]
@twang2218 
上边问题属于权限问题，解决办法：

`
docker exec gitlab update-permissions
docker restart gitlab
`
但是现在郭gitlab 邮箱出现如下问题：
Net::OpenTimeout: execution expired
找了很多方案仍然没有发出去邮箱

**Comment by twang2218** [comment]
可以参考这个文档来对邮件排障：https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/administration/troubleshooting/debug.md#mail-not-working
