### ISSUE TITLE
整个镜像打包成tar包后，迁移到其它电脑，git所有东西都丢失了。

### ISSUE THREAD

**Issue by cheneylew** [twang2218/gitlab-ce-zh#12]
1.打包已有镜像：
docker commit 3bc746c7f69e twang2218_gitlab-ce-zh_v1
docker save twang2218_gitlab-ce-zh_v1 >./twang2218_gitlab-ce-zh.tar
2.另外一台去load这个镜像：
docker load < ./twang2218_gitlab-ce-zh.tar
3./var/opt/gitlab/git-data/repositories 下面是空的

如何做才能整个git仓库也打包进去？

**Comment by twang2218** [comment]
Docker 不是这么用的，commit/save/load 命令根本就不应该作为备份之用，而且这几个命令也根本不会备份卷，自然是空的。

你应该使用 Gitlab 自身的备份恢复流程：https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/raketasks/backup_restore.md

或者直接 `tar` 备份3个卷，`config`, `data` 和 `log`，然后在新的宿主上重新建立这3个卷，并导入，但是需要注意权限。

**Comment by cheneylew** [comment]
好的 谢谢。

**Comment by twang2218** [comment]
这个文档可能更直接一些：https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/settings/backups.md#creating-backups-for-gitlab-instances-in-docker-containers

命令需要根据实际情况修改，但流程大体如此，备份数据、备份配置，然后新起服务后，导入配置导入备份。

**Comment by twang2218** [comment]
@cheneylew 问题是否已经解决了？如果问题已经解决，没有其它问题的话，可以关闭这个issue了。

**Comment by twang2218** [comment]
由于原作者没有回应，暂时关闭这个 issue，如果还有这个问题欢迎 reopen。
