### ISSUE TITLE
v8.17.2-zh 补丁有bug，请求更新到8-17-stable-zh

### ISSUE THREAD

**Issue by xujif** [twang2218/gitlab-ce-zh#15]

**Comment by xujif** [comment]
看到testing了

**Comment by xujif** [comment]
@twang2218  testing目前build出错。

**Comment by xujif** [comment]
已看到更新。

**Comment by twang2218** [comment]
嗯，`testing` 始终是跟进最新的翻译结果的，当前也就是针对 `8-17-stable-zh` 分支的最新结果。我注意到之前 `testing` 镜像构建失败，刚刚修复了问题，更新了构建脚本。
