### ISSUE TITLE
汉化版取消了代码提交必须有人review的机制(approval)?

### ISSUE THREAD

**Issue by huangjj27** [twang2218/gitlab-ce-zh#16]
对比了一下英文版(gitlab.com)以及中文版的镜像, 
其中gitlab.com上面有一个approval的机制, 必须要有人审核代码, 才能通过MR,
不知这个机制是只在gitlab.com上提供还是英文社区版也有的功能?
如果是后者, 我想知道为什么中文社区办没有这个功能 0 0

**Comment by twang2218** [comment]
@huangjj27 gitlab.com 使用的是 Gitlab EE 版本，也就是收费的企业版，这里的汉化项目基于的是 Gitlab CE 版本，也就是社区版本。这个汉化版镜像是基于 [gitlab/gitlab-ce](https://hub.docker.com/r/gitlab/gitlab-ce/)的，所以你可以直接使用同版本的 `gitlab/gitlab-ce` 替换 `twang2218/gitlab-ce-zh`，来运行，看看是否是汉化导致的功能差异。

**Comment by huangjj27** [comment]
查看过了, 并两个社区版并没有任何功能上的区别.
