### ISSUE TITLE
当在修改了容器里面的gitlab配置之后，如何重启服务

### ISSUE THREAD

**Issue by chanyying** [twang2218/gitlab-ce-zh#2]
你好有几个疑问问一下您。
当在修改了容器里面的gitlab配置之后，如何重启服务？
docker restart  <容器id> 修改的东西没有了，可以理解为本地卷宗里面的东西覆盖了容器里面的修改；
如何在重启的时候不丢东西呢？
但是在修改了卷宗里面的配置之后，重启之后，卷宗里面的修改也没有了，但是卷宗里面的数据没有丢为什么呢？

**Comment by twang2218** [comment]
具体是怎么运行的容器？挂载使用的是命名卷、匿名卷？还是绑定的宿主目录？把你具体的 `docker run` 或者 `docker-compose.yml` 文件拿来看一下。另外具体是怎么修改的配置？

**Comment by chanyying** [comment]
docker-compose.yml 就是用的你给出的docker-compose.yml，只是修改了url，现在是git clone 不下来代码。。。

**Comment by twang2218** [comment]
如果直接用的 <https://github.com/twang2218/gitlab-ce-zh/blob/master/docker-compose.yml> 的话，那么这使用的是命名卷。你不应该使用 `docker restart`，而应该使用 `docker-compose` 的命令，比如 `docker-compose down` `docker-compose up -d` 之类的。

那么你说的修改配置除了修改 `docker-compose.yml` 中的 URL 外，还修改什么了？怎么改的？另外你说的 `git clone` 不下来，具体什么情况能说清楚一些么？截图或者把操作代码贴过来。仅仅说“不行”这没法排障。给出具体信息，如果涉及 Gitlab 报错，请给出服务日志。

**Comment by chanyying** [comment]
我是用的
docker run -d \
    --hostname <这里是自己的域名> \
    -p 80:80 \
    -p 443:443 \
    --name gitlab \
    --restart unless-stopped \
    -v gitlab-config:/etc/gitlab \
    -v gitlab-logs:/var/log/gitlab \
    -v gitlab-data:/var/opt/gitlab \
    --network gitlab-net \
    twang2218/gitlab-ce-zh:8.14.0
我现在是使用的这个配置文件启动容器和服务；没有用docker-compose.yml

另外一个问题：git clone 不下来
![image](https://cloud.githubusercontent.com/assets/8544506/20860940/d05da094-b9be-11e6-8b14-eb922a5301a9.png)
我查看
![image](https://cloud.githubusercontent.com/assets/8544506/20860960/429bcc94-b9bf-11e6-9f92-d76f21eb38da.png)
我修改了gitlab-shell 里面的config也无济于事啊

**Comment by chanyying** [comment]
找了一边资料
```
gitlab_rails['internal_api_url'] = ""
```
添加了也还是出现不能使用ssh克隆代码的问题

**Comment by chanyying** [comment]
![image](https://cloud.githubusercontent.com/assets/8544506/20860998/e92e2944-b9bf-11e6-8c93-951e2d310af1.png)
今天的操作好像都没有log

**Comment by twang2218** [comment]
你这几次说的信息都不一致。最初表述是使用 `docker run`，之后又说使用项目中的 `docker-compose.yml`，而实际中你用的还是 `docker run`。而且，你给的信息也不完整，具体修改哪个文件，哪些内容？怎样重现你说的问题？你这样模棱两可说个大概是没法判断的。

此外，你贴出来的 `docker run` 中是没有映射 SSH 端口的。因此必然无法用 SSH 进行 `git clone`。而且，如果你打算使用 SSH，也必须在个人配置页面添加 SSH 公钥，这部分也没见你提及。

还有，日志时区是 UTC，0时区国际标准时间。你 +8 就是北京时间。所以不是今天没有 log，而是你算错时间了。

我这里重复了你表述的操作步骤，没有问题，无论是通过 SSH 还是 HTTP，都可以 `git clone`。

另外，这是汉化项目，你用 `gitlab/gitlab-ce:8.14.0` 代替 `twang2218/gitlab-ce-zh:8.14.0` 后，问题是不是就消失了？判断一下是不是你的使用有问题。如果严格按照我写的帮助文档中的命令执行，是不会有问题的，是不是你进行了什么修改导致的问题？
 
请把你的问题表述清楚，如何一步步重现你说的问题，具体所有的修改是什么。如果按照你说的步骤无法重现你的问题，那必然无法排障解决问题。

**Comment by chanyying** [comment]
1.我用的docker run起的镜像
2.在启动的时候关闭了22端口的映射。因为告诉我22端口已经被占用

**Comment by chanyying** [comment]
我试试打开22端口

**Comment by twang2218** [comment]
你22端口被占用自然不能用22作为gitlab的ssh 端口。这是显然的。或者你把宿主的ssh 改到别的端口，让出22来，或者你映射别的端口，比如 -p 2222:22，当然如果映射了别的端口，你 clone 的时候就必须使用ssh://的方式，而不是 git:// 的方式。

**Comment by twang2218** [comment]
另外，你要是不熟悉这些配置的话，为什么不用http 去clone?

**Comment by chanyying** [comment]
因为搭建的是内部的git。

**Comment by twang2218** [comment]
这和内部、外部没关系，没正确映射22端口自然用不了。调整一下宿主服务器的默认ssh端口即可。

**Comment by chanyying** [comment]
如果我把docker里面的映射关系就如您所说：-p 2222:22，之后我如果使用ssh克隆代码的话，应该怎么使用呢？因为如果我将宿主机上的22端口修改了，也可能导致在宿主机上克隆不下来代码吧

**Comment by twang2218** [comment]
22端口自然只有一个服务可以用，或者宿主的管理用的ssh，或者gitlab clone代码用的ssh。只有一个选择，另一个必须改。我一般是改宿主管理端口，这样gitlab 工作是最正常的。

另外你可以用http 来clone 代码。没必要非纠结ssh 。

**Comment by twang2218** [comment]
@chanyying 请问还有问题么？如果问题解决了的话，是否可以关闭这个问题？

**Comment by chanyying** [comment]
@twang2218 谢谢，最后我把ssh的22端口映射到宿主机的其他端口解决了。
