### ISSUE TITLE
配置邮件服务不成功，请问在哪里能看更多的 Debug 信息吗

### ISSUE THREAD

**Issue by yao-hang** [twang2218/gitlab-ce-zh#22]
用的 163 邮箱，按照搜索来的资料加上了`user["git_user_email"] = "xxx@163.com"` 这个字段，但是怎么弄都没成功

我去查`/var/log/gitlab`这个目录，居然是空的，请问在哪里能看到更多的 debug 信息？

**Comment by twang2218** [comment]
Docker 容器日志一般都使用标准输出，并被Docker收集，因此你可以用 `docker logs <容器ID>` 或者 `docker-compose logs <服务名>`。

**Comment by twang2218** [comment]
由于长久没有回复，关闭此issue，如果问题未解决欢迎继续提问。
