### ISSUE TITLE
修改所有用户的语言未简体中文或者默认语言怎么设置为简体中文，而不是英文？

### ISSUE THREAD

**Issue by maikebing** [twang2218/gitlab-ce-zh#27]
如题。

**Comment by twang2218** [comment]
我也不知道怎么修改默认语言，找了好几个地方，都无法改变用户 "Preferred language" 都是 English 的情况。

**Comment by maikebing** [comment]
好吧。

**Comment by twang2218** [comment]
找到了一个地方，在谢航的汉化项目提交了 MR，<https://gitlab.com/xhang/gitlab/merge_requests/31> 已经被合并。现在的 `twang2218/gitlab-ce-zh:testing` 是对应 `10-4-stable-zh` 分支最新的结果，包含默认设为简体中文的补丁，可以尝试一下。
