### ISSUE TITLE
当点击项目页面的blame按钮时，server 500

### ISSUE THREAD

**Issue by gomaster-me** [twang2218/gitlab-ce-zh#28]
==> /var/log/gitlab/gitlab-rails/production.log <==
Started GET "/-/metrics" for 127.0.0.1 at 2017-08-17 07:48:59 +0000
Processing by MetricsController#index as HTML
Filter chain halted as :validate_prometheus_metrics rendered or redirected
Completed 404 Not Found in 1ms (Views: 0.4ms | ActiveRecord: 0.0ms)
Started GET "/root/hello-ci-cd/blame/master/Dockerfile" for 211.103.184.74 at 2017-08-17 07:48:59 +0000
Processing by Projects::BlameController#show as HTML
  Parameters: {"namespace_id"=>"root", "project_id"=>"hello-ci-cd", "id"=>"master/Dockerfile"}
Completed 500 Internal Server Error in 39ms (ActiveRecord: 1.5ms)

ActionView::Template::Error (divided by 0):
    17:           - @blame_groups.each do |blame_group|
    18:             %tr
    19:               - commit = blame_group[:commit]
    20:               %td.blame-commit{ class: age_map_class(commit.committed_date, project_duration) }
    21:                 .commit
    22:                   = author_avatar(commit, size: 36)
    23:                   .commit-row-title
  app/helpers/blame_helper.rb:18:in `/'
  app/helpers/blame_helper.rb:18:in `age_map_class'
  app/views/projects/blame/show.html.haml:20:in `block in _app_views_projects_blame_show_html_haml___3590071031727739669_70278570072800'
  app/views/projects/blame/show.html.haml:17:in `each'
  app/views/projects/blame/show.html.haml:17:in `_app_views_projects_blame_show_html_haml___3590071031727739669_70278570072800'
  lib/gitlab/i18n.rb:45:in `with_locale'
  lib/gitlab/i18n.rb:51:in `with_user_locale'
  app/controllers/application_controller.rb:294:in `set_locale'
  lib/gitlab/performance_bar/peek_performance_bar_with_rack_body.rb:16:in `call'
  lib/gitlab/middleware/multipart.rb:93:in `call'
  lib/gitlab/request_profiler/middleware.rb:14:in `call'
  lib/gitlab/middleware/go.rb:16:in `call'
  lib/gitlab/etag_caching/middleware.rb:11:in `call'
  lib/gitlab/request_context.rb:18:in `call'
  lib/gitlab/metrics/requests_rack_middleware.rb:27:in `call'

**Comment by twang2218** [comment]
我在 `9.4.4` ~ `9.5.4` 上重现了这个问题，Gitlab 官方镜像 `gitlab/gitlab-ce` 有同样的问题，所以应该是 GitLab 本身的问题。这个问题在 `9.5.5` 之后的版本上就消失了，可以使用之后的版本。
