### ISSUE TITLE
用docker-compose的方式安装完之后访问报502错误

### ISSUE THREAD

**Issue by qizhijun** [twang2218/gitlab-ce-zh#29]
安装的版本是 9.5.4，安装完后能正常启动，但是网页访问的是：哇，GitLab 响应花费了太多时间。

**Comment by qizhijun** [comment]
在百度搜索类似的问题有人回答说是，汉化包的版本使用的不对，请问该如何解决呢。

**Comment by twang2218** [comment]
一般需要一些时间启动，稍等一段时间再看看。

**Comment by twang2218** [comment]
长时间没有新的信息，暂时关闭该 issue，如果还有问题，欢迎重新开启。
