### ISSUE TITLE
windows10下挂载本地目录的时候，无法启动

### ISSUE THREAD

**Issue by tomcruce** [twang2218/gitlab-ce-zh#30]
GITLAB_VERSION=v9.0.6
执行docker run命令
docker run --detach \
    --hostname localhost \
    --publish 8443:443 --publish 10020:80 --publish 2222:22 \
    --name gitlab \
    --restart always \
    --volume D:/work/git/gitlab/config:/etc/gitlab \
    --volume D:/work/git/gitlab/logs:/var/log/gitlab \
    --volume D:/work/git/gitlab/data:/var/opt/gitlab \
    twang2218/gitlab-ce-zh:latest
后无法启动，查看日志
Failed asserting that ownership of "/var/opt/gitlab/git-data" was git
---- Begin output of set -x && [ "$(stat --printf='%U' $(readlink -f /var/opt/gitlab/git-data))" = 'git' ] ----
STDOUT:
STDERR: + readlink -f /var/opt/gitlab/git-data
+ stat --printf=%U /var/opt/gitlab/git-data
+ [ root = git ]

应该是权限问题

但是如果不挂载本地目录的话，可以正常启动，不确定是什么原因，请指教，谢谢！

**Comment by twang2218** [comment]
一般不推荐挂载宿主目录，否则权限问题会比较麻烦。因此在例子中，都使用的是卷。

Windows一直都有共享目录问题，特别是 docker toolbox。如果你换到 docker for windows 可能会好一些。

**Comment by tomcruce** [comment]
我用的就是docker for windows，如果不挂载宿主目录的话，我在gitlab配置的东西，如果docker 重启  ，所有的操作就都丢失了，
