### ISSUE TITLE
10.x 版本需要编译 po 文件

### ISSUE THREAD

**Issue by tnextday** [twang2218/gitlab-ce-zh#35]
```shell
sudo -u git -H bundle exec rake gettext:pack RAILS_ENV=production
sudo -u git -H bundle exec rake gettext:po_to_json RAILS_ENV=production
```

参考 https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/install/installation.md#compile-gettext-po-files

**Comment by twang2218** [comment]
我在 10.0 的 Dockerfile 中已经加入了构建 gettext 的部分：

https://github.com/twang2218/gitlab-ce-zh/blob/master/10.0/Dockerfile#L56

```Dockerfile
...
    && bundle exec rake gettext:compile \
    && bundle exec rake gitlab:assets:compile \
...
```

**Comment by tnextday** [comment]
命令已经改了，看这个提交
https://gitlab.com/gitlab-org/gitlab-ce/commit/26ff4e3984558441ca11191678a7524dd91b146a
