### ISSUE TITLE
经常崩溃是什么原因

### ISSUE THREAD

**Issue by ancon** [twang2218/gitlab-ce-zh#36]
Ubuntu16.04 docker版本为17-ce-05.
2核4G内存。阿里云服务器

**Comment by VAllens** [comment]
Gitlab版本号是多少，9.5.2(含)以下没问题，以上不稳定。
可以试试10.1.0版本。
PS:硬件配置太低了。
想要Gitlab运行得算过得去，至少4核8G内存。
想要Gitlab运行得四化畅快，至少8核16G内存。
毕竟你用的是集成版，一个docker镜像里包含了所有依赖应用，个个都是吃硬件大户。
除非你分开多个服务器部署，并且配置它们之间的依赖关系。
这样的话，单个服务器的配置可以低一些，2核4G内存也可以。

**Comment by ancon** [comment]
@VAllens 说的很有道理，已经弃用。。。
最终团队使用的是 gitlab官方原版，好像快很多。也不闪退了，等docker版本做的好一点，优化得更省资源再说吧。
同是阿里云2核4G，开了docker不下6个，没有任何问题。

**Comment by VAllens** [comment]
我运行`Gitlab`的服务器配置是`8核16G内存` :)

**Comment by twang2218** [comment]
@ancon 如果是闪退的话，`docker logs` 中或许可以看到日志，如果对比官方的 `gitlab/gitlab-ce` 同等版本的镜像，看看是不是都有问题，如果只有汉化版有问题，可以看一下是不是汉化过程中导致了某些错误。

另外，现在在重新构建 9.5 以及10.0 分支的镜像，如果是由于之前 `yarn.lock` 删除导致的前端故障，这部分应该会修复。

**Comment by twang2218** [comment]
长时间未回复，关闭 issue。如果还有问题可以重新开启。
