### ISSUE TITLE
9.5.2升级到10.0.3后又回退到9.5.2出现的若干个问题

### ISSUE THREAD

**Issue by VAllens** [twang2218/gitlab-ce-zh#38]
1.原先可以正常使用LDAP登录的，回退后无法使用LDAP认证登录。
2.原先每次push提交都会触发gitlab-runners自动构建，回退后不会触发构建。

**Comment by maikebing** [comment]
你的 LDAP 的gitlab 账号能给我一个吗？我想测试 我的GitLab.Visual Studio 插件？

**Comment by VAllens** [comment]
@maikebing 是公司的LDAP账号，所以不外传。
你可以自己搭建一台LDAP服务器，然后在Gitlab配置LDAP后，进行测试。

**Comment by twang2218** [comment]
@VAllens 请测试一下新的版本是否还有问题，如果新做的镜像修复了这个问题那么就可以关闭这个 issue 了。

**Comment by VAllens** [comment]
Okey
