### ISSUE TITLE
不更新了吗?

### ISSUE THREAD

**Issue by maikebing** [twang2218/gitlab-ce-zh#41]
?

**Comment by maikebing** [comment]
@twang2218  可否建立一个组织， 然后让大家来维护， 现在是你私人项目， 只能你来维护。

**Comment by maikebing** [comment]
https://github.com/gitlab-ce-zh/gitlab-ce-zh  
这继续维持吧？有参与的加入一下吧。

**Comment by twang2218** [comment]
非常抱歉，前段时间事情比较杂乱，一直没能抽出时间来修复构建问题，这几天有时间，我会把问题一一修复，并且继续发布更新。从长远角度看，Gitlab 应该会越来越多的扩展国际化的部分，希望能有一天直接使用官方镜像就可以，而不用再使用该汉化补丁的 docker 镜像了。
