### ISSUE TITLE
manifest for twang2218/gitlab-ce-zh:10.0.3 not found

### ISSUE THREAD

**Issue by hexiaoyun128** [twang2218/gitlab-ce-zh#42]
使用docker-compose.yml 
docker-compose up就出现下面的错误：
Creating network "gitlab_default" with the default driver
Creating volume "gitlab_data" with default driver
Creating volume "gitlab_config" with default driver
Creating volume "gitlab_logs" with default driver
Pulling gitlab (twang2218/gitlab-ce-zh:10.0.3)...
ERROR: manifest for twang2218/gitlab-ce-zh:10.0.3 not found

**Comment by twang2218** [comment]
十分抱歉，之前构建有问题，发现10.0.x的镜像的 JS 资源都不完整，因此为了避免别人误装，删除了这几个镜像，原计划随后就修复，后来一直有很多事情没能抽出时间，现在正在构建 10.0.3，应该之后就可以了。

**Comment by twang2218** [comment]
长时间未回复，关闭 issue。如果还有问题可以重新开启。
