### ISSUE TITLE
docker-compose 运行 10.3 版本 使用root/5iveL!fe 账号密码登录 密码错误。 

### ISSUE THREAD

**Issue by zhangmz0223** [twang2218/gitlab-ce-zh#44]
初始密码不是5iveL!fe？？

使用的是 根目录下面的 docker-compose.yml 文件。无任何修改，请问如何修改 通过数据库修改账号密码？

**Comment by twang2218** [comment]
初始密码是第一次访问时设置的，不再使用默认密码的形式了。

**Comment by zhangmz0223** [comment]
@twang2218 

点错了，已经找到问题了。
配置里写了，使用域名访问。
所以，使用IP访问会无法出现初始密码界面。
另外运行了一段时间后，访问会变慢，是什么原因？
