### ISSUE TITLE
docker-compose up met ERROR: timex collector failed

### ISSUE THREAD

**Issue by xiaoping378** [twang2218/gitlab-ce-zh#45]
HI 感谢你的辛苦贡献，但我发现从docker-compose启动的话，会遇到

ERROR: timex collector failed

和这里描述一致，[这里](https://github.com/prometheus/node_exporter/issues/711), 看看是不是有时间修复下

**Comment by twang2218** [comment]
使用官方 `gitlab/gitlab-ce` 镜像也有同样的问题么？可以替换同版本的试一下，如果同样有问题的话，建议到上游 [GitLab CE 项目](https://gitlab.com/gitlab-org/gitlab-ce/)上发 Issue，这样汉化项目自然也会受益。

**Comment by twang2218** [comment]
现在还有这个问题么？如果已经在新版本修复了的话，那么就可以关闭 issue 了，谢谢。
