### ISSUE TITLE
centos7 宿主机等待了很久 都是502 

### ISSUE THREAD

**Issue by wuweiit** [twang2218/gitlab-ce-zh#46]
centos7 宿主机等待了很久 都是502 ，使用官方英文版镜像无问题可正常启动。

摘取的错误日志：
gitlab_1  | ==> /var/log/gitlab/unicorn/unicorn_stdout.log <==
gitlab_1  | bundler: failed to load command: unicorn (/opt/gitlab/embedded/bin/unicorn)
gitlab_1  | 
gitlab_1  | ==> /var/log/gitlab/unicorn/unicorn_stderr.log <==
gitlab_1  | SyntaxError: /opt/gitlab/embedded/service/gitlab-rails/app/models/deploy_keys_project.rb:12: invalid multibyte char (UTF-8)
gitlab_1  | /opt/gitlab/embedded/service/gitlab-rails/app/models/deploy_keys_project.rb:12: invalid multibyte char (UTF-8)
gitlab_1  | /opt/gitlab/embedded/service/gitlab-rails/app/models/deploy_keys_project.rb:12: invalid multibyte char (UTF-8)

**Comment by wuweiit** [comment]
/opt/gitlab/embedded/service/gitlab-rails/app/models/deploy_keys_project.rb
容器内这个文件的12行有个乱码，将乱码去掉就解决了，能正常进入登录界面。

**Comment by twang2218** [comment]
你说的可能是这个 issue：https://gitlab.com/xhang/gitlab/issues/50 ，我已经提交了 Merge Request: https://gitlab.com/xhang/gitlab/merge_requests/27

**Comment by wuweiit** [comment]
是docker版的有问题：https://hub.docker.com/r/twang2218/gitlab-ce-zh/

**Comment by twang2218** [comment]
@wuweiit Docker 使用的是 xhang 维护的汉化版本，因此如果汉化版本有问题，该 Docker 镜像一样会有问题，需要先修复上游汉化项目。现在上游已经合并了我提交的，这里也重新构建了受影响的 `10.1.7` 、 `10.2.7`， `10.3.5` 镜像，现在应该可以正常工作了。可以测试一下，如果没问题就可以关闭 issue 了。

**Comment by wuweiit** [comment]
自己服务器做了一个修改commit到本地了，先用着等必要时来看看，新版本镜像吧。
