### ISSUE TITLE
请问从8.16.5升级到最新版本 看启动日志在数据库迁移的时候总是失败 然后重启 有解决方案么？

### ISSUE THREAD

**Issue by wbdosx** [twang2218/gitlab-ce-zh#47]
请问从8.16.5升级到最新版本 看启动日志在数据库迁移的时候总是失败 然后重启 有解决方案么？

**Comment by twang2218** [comment]
二者之间的版本差距有些大，没有这么升级过。你可以尝试一下先升级到9.x，然后再升级到10.x，这些版本的 Docker 镜像都有。另外，这个是升级迁移问题，不属于汉化镜像的制作问题，建议参考一下官方文档，如：https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update 。以及碰到这类升级失败，可以在 GitLab CE 的问题列表发 issue：https://gitlab.com/gitlab-org/omnibus-gitlab/issues

**Comment by twang2218** [comment]
长时间没有回复，先关闭这个 issue，有镜像问题可以再提。
