### ISSUE TITLE
找不到10.6.0的docker镜像

### ISSUE THREAD

**Issue by qq253498229** [twang2218/gitlab-ce-zh#51]
Error response from daemon: manifest for twang2218/gitlab-ce-zh:10.6.0 not found

**Comment by qq253498229** [comment]
![wx20180402-234736](https://user-images.githubusercontent.com/31200516/38203005-52b71f86-36d0-11e8-84e3-ececc945a1b7.png)

**Comment by twang2218** [comment]
现在应该可以了，之前是上游汉化存在问题，所以虽然dockerfile 改了，但是镜像无法构建，现在已经好了。
