### ISSUE TITLE
仓库卷在windows上面不能配置到本地目录

### ISSUE THREAD

**Issue by coolazrael** [twang2218/gitlab-ce-zh#52]
```
volumes:
        - config:/etc/gitlab
        - /d/docker/data/gitlab_data:/var/opt/gitlab/git-data
        - logs:/var/log/gitlab
```
然后执行·`docker-compose up` 命令会出现以下问题
![tim 20180403213000](https://user-images.githubusercontent.com/3381250/38252263-411a1b28-3786-11e8-861e-a98a3832bdf3.png)

**Comment by twang2218** [comment]
如果你是Windows环境，那么不建议挂载到本地，Windows文件系统和Linux差异比较大，可能会导致问题。

**Comment by twang2218** [comment]
使用 Docker，特别是 Windows 系统，不应该使用挂本地目录的办法，应该使用卷，也就是 Docker volume。

另外，这个问题许久没有新的信息，暂且关闭，有问题可以继续讨论。
