### ISSUE TITLE
hi,怎么升级gitlab版本

### ISSUE THREAD

**Issue by huaijinwoyu** [twang2218/gitlab-ce-zh#53]
RT，之前我是用 Docker Compose 安装的10.4.6版本。现在想升级到10.6.1版本，怎么升级呢？我担心数据会丢失，所以不敢用官方提供的升级办法。请问有好办法吗？

**Comment by twang2218** [comment]
先将卷的数据备份，然后再升级，最好是小版本的升级，而不要跨越太大。比如先升到10.5.x 。另外也可以先利用备份在另一个机器上做升级实验，确认没问题后再正式升级。

**Comment by twang2218** [comment]
长久没有新的信息，暂且关闭，有问题可以继续提问。
