### ISSUE TITLE
9.5.5到10.6.x各种不兼容，如何处理？

### ISSUE THREAD

**Issue by flycloudOne** [twang2218/gitlab-ce-zh#58]
@twang2218     我们公司现在用的9.5.5，如何在能平滑的升级到10+，解决兼容问题（已经star）

**Comment by loverto** [comment]
不要大版本升级，先小版本升级9.6，9.7，9.8，10这种思路，试试

**Comment by twang2218** [comment]
升级的问题应该参考官方文档，并且尽量小版本升级，而不是跨很多版本升级。

https://docs.gitlab.com/omnibus/docker/README.html#upgrade-gitlab-to-newer-version
https://docs.gitlab.com/omnibus/update/README.html

**Comment by flycloudOne** [comment]
@loverto @twang2218 好的，我门先测试一下

**Comment by flycloudOne** [comment]
9.5.5->9.5.10->10.0.0->10.1->10.2->10.3......->10.8

问题解决！！！
谢谢 @twang2218 @loverto
