### ISSUE TITLE
使用docker-compose.yml配置邮件问题

### ISSUE THREAD

**Issue by xinyin025** [twang2218/gitlab-ce-zh#59]
通过docker-compose.yml方式来启动gitlab，配置了QQ企业邮，收到如下退信。

无法与收件人（admin@example.com）所在服务商建立连接，收件人域名可能不存在。 
connect to example.com[93.184.216.34]: Connection timed out (port 25)

请问这个在哪里修改。

**Comment by twang2218** [comment]
呃，example.com 是例子，这里只是演示如何将 GitLab 中的配置和 `docker-compose.yml` 里的配置结合起来。你应该根据自己的具体情况来配置，具体 GitLab 的配置参数应该参考 GitLab 的官方文档。

https://docs.gitlab.com/omnibus/settings/smtp.html

另外，提问题也应该将具体的配置，以及重现问题的方式的细节说清楚。

**Comment by xinyin025** [comment]
了解，感谢指导。
