### ISSUE TITLE
gitlab Forbidden了怎么解决呢？

### ISSUE THREAD

**Issue by chanyying** [twang2218/gitlab-ce-zh#6]
![image](https://cloud.githubusercontent.com/assets/8544506/21453530/fb0575ce-c94a-11e6-9910-64439d69cd23.png)
自从搭建起来之后，就没有碰过，docker服务正常，gitlab重启后无效，查看日志，显示gitlab-workhorse和nginx报错403，页面上显示Forbidden,因为是突然出现这样的问题的。

**Comment by twang2218** [comment]
@chanyying 在提问前，请仔细阅读这篇文章：<https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md>

**Comment by chanyying** [comment]
![image](https://cloud.githubusercontent.com/assets/8544506/21453530/fb0575ce-c94a-11e6-9910-64439d69cd23.png)
自从搭建起来之后，就没有碰过，docker服务正常，gitlab重启后无效，查看日志，显示gitlab-workhorse和nginx报错403，页面上显示Forbidden,因为是突然出现这样的问题的。

**Comment by twang2218** [comment]
你应该提供帮助排障的具体信息，完整日志是一方面，具体执行的命令，`docker-compose.yml` 的内容。如何可以让我这里重现你的问题。不能在别的地方重现的问题，基本是没有办法去判断和解决的，都只能猜来猜去的浪费时间。如果问题解决，应该给出问题的原因和解决方式，方便其他有同样问题的人看到这个 issue 的时候知道如何解决。
