### ISSUE TITLE
使用docker-compose来启动时，数据库有一个错误

### ISSUE THREAD

**Issue by xinyin025** [twang2218/gitlab-ce-zh#61]
docker-compose.yml文件如下
![](https://s1.ax1x.com/2018/06/04/CTg3mq.png)
启动命令为docker-compose up -d
错误内容如下图
![avatar](https://s1.ax1x.com/2018/06/04/CTgMlj.png)

**Comment by twang2218** [comment]
这应该是 gitlab 的问题，应该到 GitLab 官方 issue 列表中发 issue，链接在首页中有。
另外 10.8.3 中应该修复了这个问题，https://gitlab.com/gitlab-org/gitlab-ce/issues/46717
