### ISSUE TITLE
10.8.4 新建合并请求 不显示分支

### ISSUE THREAD

**Issue by echoescn** [twang2218/gitlab-ce-zh#63]
10.8.4 新建合并请求 不显示分支，搜索也不显示接口，看异步接口已经请求，前端未显示

**Comment by echoescn** [comment]
我发现所有版本都有这个问题
![](https://ws3.sinaimg.cn/large/006tKfTcly1fsr25gcp9pj30ys11ujwk.jpg)

**Comment by twang2218** [comment]
这个问题不是镜像问题，是官方汉化出了问题：

* https://gitlab.com/gitlab-org/gitlab-ce/issues/46654
* https://gitlab.com/xhang/gitlab/issues/64

官方已经有修复补丁，可能会在 `11.1` 版本发布时正式修复。

* https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/20016

暂时可以切换为英文。
