### ISSUE TITLE
About ARM architecture support and command, "docker network" purpose?

### ISSUE THREAD

**Issue by ucantcode** [twang2218/gitlab-ce-zh#64]
Is this able to run on Raspberry or ARM architecture? I had tried this. It seems not to run well. 
Secondly, it this able to run under an isolated network environment such as "apache virtualhost"? I don't fully understand what is the command "docker network network-name". So, I guess this purpose similar to "apache virtualhost".

**Comment by twang2218** [comment]
`docker network` is docker's network model, it will set up a local network to connect between docker containers. It's not necessary to have an external Internet connection. However, this Docker image is based on GitLab official docker image, which is not a multi-arch image if I understand correctly, therefore, it can only run on x64 arch.

You can check https://forum.gitlab.com/c/arm-devices for more related topics. However, as GitLab is memory hunger, I will suggest you try [Gogs](https://gogs.io/) or [Gitea](https://gitea.io/en-us/), they are written in Golang, much lightweight and can be run on an ARM system.

**Comment by twang2218** [comment]
closed as not an issue of this project.
