### ISSUE TITLE
配置邮箱错误

### ISSUE THREAD

**Issue by XuDL** [twang2218/gitlab-ce-zh#65]
使用 docker-compose 部署，按照网上包括官网的邮箱配置方法配置了好多次，配置的邮箱是腾讯企业邮箱，发送邮件的时候 log 始终提示：

```
SocketError: getaddrinfo: Temporary failure in name resolution
from /opt/gitlab/embedded/lib/ruby/2.4.0/net/smtp.rb:539:in `initialize'
from /opt/gitlab/embedded/lib/ruby/2.4.0/net/smtp.rb:539:in `open'
from /opt/gitlab/embedded/lib/ruby/2.4.0/net/smtp.rb:539:in `tcp_socket’
...
```

请教下这种情况如何解决？

**Comment by XuDL** [comment]
补充一下，刚才用 docker run 运行了一下镜像，邮箱就可以正常发送，但是换回 docker-compose 的方式运行就依然报错，贴上 docker-compose 的配置

`version: '2'
services:
  gitlab:
      image: 'docker.io/twang2218/gitlab-ce-zh:latest'
      restart: unless-stopped
      hostname: 'gitlab.xx.xx'
      dns_search: exmail.qq.com
      environment:
        TZ: 'Asia/Shanghai'
        GITLAB_OMNIBUS_CONFIG: |
            external_url 'https://xx.xx.xx'
            gitlab_rails['time_zone'] = 'Asia/Shanghai'
            gitlab_rails['smtp_enable'] = true
            gitlab_rails['smtp_address'] = "smtp.exmail.qq.com"
            gitlab_rails['smtp_port'] = 465
            gitlab_rails['smtp_user_name'] = ‘xx@xx.com'
            gitlab_rails['smtp_password'] = ‘xxx'
            gitlab_rails['smtp_authentication'] = "login"
            gitlab_rails['smtp_enable_starttls_auto'] = true
            gitlab_rails['smtp_tls'] = true
            gitlab_rails['gitlab_email_from'] = ‘xx@xx.com'
            gitlab_rails['smtp_domain'] = "exmail.qq.com"
      ports:
        - '8012:80'
      volumes:
        - /root/gitlab/config:/etc/gitlab
        - /root/gitlab/data:/var/opt/gitlab
        - /root/gitlab/logs:/var/log/gitlab`

**Comment by twang2218** [comment]
你 `docker run` 具体的命令是什么？

**Comment by XuDL** [comment]
是这个，这个启动的目前一切正常，邮箱也可以正常使用，邮箱中链接也可以访问
docker run -d --name gitlab \
--hostname gitlab.xxx.xx \
-p 8012:80 \
-v /root/gitlab/config:/etc/gitlab \
-v /root/gitlab/data:/var/opt/gitlab \
-v /root/gitlab/logs:/var/log/gitlab \
-e TZ=Asia/Shanghai \
--restart=always \
docker.io/twang2218/gitlab-ce-zh

**Comment by twang2218** [comment]
`docker-compose.yml` 的例子是使用 Docker 卷的，而不是挂载本地磁盘路径，因此其中的初始配置是来自于 `GITLAB_OMNIBUS_CONFIG` 这个环境变量。而你这里将卷改为了挂载本地磁盘路径，因此会导致这个配置可能无法生效。

建议是，或者你改回默认的卷的形式试一下看看有没有问题；或者既然你使用的是自己的配置文件，那么去掉 `GITLAB_OMNIBUS_CONFIG`，避免干扰。

另外一个可能的问题是，注意一下你的邮件服务器是否为内网服务器？其 IP 网段是不是和 Docker 内置网络的网段产生了冲突？

**Comment by XuDL** [comment]
收到~多谢~

**Comment by grusirna** [comment]
您好，我使用阿里云邮箱，始终配置不成功。具体问题出在哪里不知道在哪里可以看，还望指教，谢谢

**Comment by twang2218** [comment]
@grusirna 这么问问题没法回答，请提供具体的配置和重现步骤，以及出错的日志。
