### ISSUE TITLE
ssh免密配置后 clone 不停的提示password

### ISSUE THREAD

**Issue by abc-ziv** [twang2218/gitlab-ce-zh#67]
➜  www git clone ssh://git@192.168.10.174:2018/zhijia/laradock.git
正克隆到 'laradock'...
git@192.168.10.174's password: 
Permission denied, please try again.
git@192.168.10.174's password: 
Permission denied, please try again.
git@192.168.10.174's password: 
Permission denied (publickey,password).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by twang2218** [comment]
请提供具体的配置。

**Comment by abc-ziv** [comment]
找到问题了。 ssh 我开启的是2018端口 把容器22端口映射到本机2018端口没有生效。 目前我修改了docker-compose.yml 部分参数。

**Comment by twang2218** [comment]
👏。可以分享一下正确的配置，以后别人有这个问题可以参考你的配置。另外，如果没有额外的问题可以关闭这个issue。
