### ISSUE TITLE
11.1.1版本点击合并请求页时cpu会到100%并导致504

### ISSUE THREAD

**Issue by callect** [twang2218/gitlab-ce-zh#68]
如题，切换到11.1.0时故障消除

**Comment by twang2218** [comment]
看一下 docker logs 的日志有什么报错。

**Comment by twang2218** [comment]
上游汉化项目有个修复可能与这个 bug 相关：
https://gitlab.com/xhang/gitlab/commit/abce88c33aaf18f06a2bce1529984b5d1d61c2e4

可以尝试一下 `11.1.2` 以后的镜像是否修复了这个问题。

**Comment by callect** [comment]
好的
