### ISSUE TITLE
有没有考虑过通过 svnsrv 支持 svn  ？

### ISSUE THREAD

**Issue by maikebing** [twang2218/gitlab-ce-zh#69]
https://gitee.com/oschina/svnsrv

**Comment by twang2218** [comment]
我已经许多年都没有使用过 svn 了，差不多10年前 Git 就已经在版本控制多家软件中占了主导了，所以我觉得支持回 svn 是一个后退，svnsrc 这个项目也是基本没人更新了。

而且这个项目是围绕着 GitLab 汉化项目，将其制作为镜像方便使用。所以不在 GitLab 项目中的东西，不应该加入到这个项目的镜像中。不过 Docker 非常适合重用已有资源，如果你需要的话，可以基于这个项目镜像定制自己有特殊需求的镜像。比如，写个 `Dockerfile`：

```Dockerfile
FROM twang2218/gitlab-ce-zh:11.1.4

RUN ...
```

**Comment by maikebing** [comment]
latest  还是 11.0 ,不是 11.1.4 ，

**Comment by maikebing** [comment]
svn 我就是听一下你的想法， 因为 很多 人  落后点的地方 ， 只会用svn, 比较麻烦。

**Comment by twang2218** [comment]
😓，latest...，我又忘了更新 Docker Hub了，现已更新。

**Comment by maikebing** [comment]
你经常忘记。 啊哈
