### ISSUE TITLE
js汉化未生效

### ISSUE THREAD

**Issue by hyt7212** [twang2218/gitlab-ce-zh#9]
版本8.14  
app/assets/javascripts/milestone_select.js  
源码汉化是有替换成功，但是  
/opt/gitlab/embedded/service/gitlab-rails/public/assets  
目录下打包后的js文件还是未汉化的代码

**Comment by twang2218** [comment]
确实存在这个问题，应该是由于 assets 未能重新编译导致。应该需要执行 `bundle exec rake assets:precompile RAILS_ENV=production` 重新编译 assets。我看一下怎么修改一下镜像脚本可以让其重新编译一下，并放入镜像。

**Comment by twang2218** [comment]
临时的解决办法是在容器启动后，利用 `docker exec` 执行该命令：

```bash
$ docker exec -it <容器ID> 'gitlab-rake assets:precompile RAILS_ENV=production'
```

**Comment by hyt7212** [comment]
OK，多谢！

**Comment by twang2218** [comment]
@hyt7212 我修改了 Dockerfile，重新编译了资源文件，从 `8.12` - `8.16` 都已经是新的镜像。你可以尝试一下是不是已经解决这个问题了。
